# This is a basic workflow to help you get started with Actions

name: My-GitHub-Actions
env:
  APPLICATION_NAME: "My_app"
  PACKAGE_NAME: "App-deploy-ver-${{ github.sha }}"


on:
  push:
    branches:
      - main
jobs:
  my_testing:
  
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello Message
      run: echo "Hello World from Testing job"
      
    - name: Execure few commands
      run: |
        echo "Hello Message1"
        echo "Hello Message1"
        echo "Aplication name: ${{ env.APPLICATION_NAME }}"

  


  my_deploy:
  
    runs-on: ubuntu-latest
    needs: [my_testing]
    steps:
    - name: Print Hello Message
      run: echo "Hello World from Deploy job"
      
    - name: Printing deployment package
      run: echo "Deploy package name is ${{ env.PACKAGE_NAME }}"
